config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'events_api#redirect', as:'redirect'
  get '/callback', to: 'events_api#callback', as:'callback'
  get '/calendars', to: 'events_api#calendars', as: 'calendars'
  get '/events_api/:calendar_id', to: 'events_api#retrieve_events', as: 'events_api', calendar_id: /[^\/]+/
  resources :events, controller: 'events'

  resources :meetings
  namespace :admin do
    root 'application#index'
    resources 'users' do
      member do
        patch :archive
      end
    end
    resources 'programs'
    resources 'materials'
    resources 'machines'
    resources 'occupation'
    resources 'rentings'
    resources 'information'
    resources 'fabmoments' do
      member do
        get :staff_pick
      end
    end
    resources 'events' do
      member do
        get :approved
      end
    end
    get 'fabmanager_settings/1', to: 'fabmanager_settings#settings'
    resources 'fabmanager_settings', only: [:update]
  end

  devise_for :users

  resources 'information'
  resources 'users'
  resources :avatar
  resources 'machines' do
    member do
      get :take
      get :leave
    end
  end



  root 'fabmoments#index'
  get '/fabmoment/index', :controller => 'fabmoments', :action => "index"
  post '/fabmoment/index', :controller => 'fabmoments', :action => "index"

  resources 'fabmoments' do
    member do
      get :like
      get :unlike
    end
    collection do
      get :search
    end
    resources 'tags' do
      member do
        delete :remove
      end
    end
    resources 'project_files', only: [:create, :destroy]
    resources 'comments', only: [:create, :edit, :update, :destroy]
  end
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :feeds, :dependent => :destroy
  has_many :machines, :through => :feeds

  def full_name
    if name? && thickness?
      "#{name} #{sort} #{thickness}mm"
    elsif name == nil
      sort.capitalize! if sort.start_with?(sort.downcase)
      if thickness?
      "#{sort} #{thickness}mm"
      else
        "#{sort}"
      end
    else
      "#{name} #{sort}"
    end
  end
end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < ApplicationController
	before_action :set_material, only: [:show, :edit, :update, :destroy, :archive]
	def index
		@materials = Material.all
	end
	def new
		@materials = Material.new
	end
  def show
  end
  def edit
  end
     def update
    @material = Material.find(params[:id])
    if @material.update(material_params)
      flash[:notice] = "Machine is succesvol geëdit."
      redirect_to admin_materials_path
    else
      render 'edit'
    end
  end
	def create
		@materials = Material.new(material_params)

    if @materials.save
      flash[:notice] = "Matriaal is succesvol toegevoegd."
      redirect_to admin_materials_path
    else
      flash.now[:alert] = "Matriaal is niet toegevoegd."
    end
	end
	 def destroy
    @materials = Material.find(@materials)
    @materials.delete
    redirect_to admin_materials_path
  end
    def material_params
    	params.require(:material).permit(:id,:sort,:name,:thickness,:admin)
    end
    def set_material
    @materials = Material.find(params[:id])
  	end
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/views/admin/materials/_form.html.erb
<div class="w3-row">
	<div class="w3-half w3-center" style="margin-left: 25%">
		<%= simple_form_for [:admin, @materials] do |f| %>
			<!-- Input -->
			<%= f.input_field :sort, required: true, autofocus: true %>
			<%= f.label :sort %>
			<%= f.error :admin %>
			<%= f.input_field :name, required: true, autofocus: true %>
			<%= f.label :name %>
			<%= f.error :admin %>
			<%= f.input_field :thickness, required: true, autofocus: true %>
			<%= f.label :thickness %>
			<%= f.error :admin %>
			<br><br>
      <!-- Zenden -->
      <div class="w3-center w3-margin-bottom">
        <%= f.button :button, class: "w3-btn w3-blue w3-center" %>
      </div>

		<% end %>
	</div>
</div>

app/views/admin/materials/edit.html.erb
<div class="w3-container w3-margin-top">
	<header>
		<h2 class="w3-center">Nieuw Materiaal</h2>
	<header>
</div>

<%= render "form", material: @material %>

app/views/admin/materials/index.html.erb
<% title("Material", "Admin") %>
<p>
<ul>
  <div class="row">
    <div class="col w3-card w3-round-xlarge">
      <div class="w3-margin-left w3-margin-bottom">
        <div class="w3-bottombar w3-border-blue-gray">
        <h1>Materialen:</h1>
      </div>
      <% @materials.each do |material| %>
          <li><%= material.sort %></li>
          <li><%= material.name %></li>
          <li><%= material.thickness %></li>

          <%= link_to admin_material_path(material), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger w3-round-xlarge"  do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
          <%= link_to edit_admin_material_path(material), class:"btn btn-warning w3-round-xlarge"  do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
      <% end %>
        <div class="w3-topbar w3-border-blue-gray w3-margin-top">
          <%= link_to "Nieuw Materiaal", [:new, :admin, :material],
                      class: "new w3-btn w3-lime w3-margin-bottom w3-margin-top w3-round-xlarge w3-topbar w3-border-blue-gray w3-hover-blue"%>
        </div>
      </div>
    </div>
  </div>
</ul>
</p>

app/views/admin/materials/new.html.erb
<% title("Nieuw", "Machine") %>

<div class="w3-container w3-margin-top">
	<header>
		<h2 class="w3-center">Nieuw Materiaal</h2>
	<header>
</div>

<%= render "form", material: @material %>