config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'events_api#redirect', as:'redirect'
  get '/callback', to: 'events_api#callback', as:'callback'
  get '/calendars', to: 'events_api#calendars', as: 'calendars'
  get '/events_api/:calendar_id', to: 'events_api#retrieve_events', as: 'events_api', calendar_id: /[^\/]+/
  resources :events, controller: 'events'

  resources :meetings
  namespace :admin do
    root 'application#index'
    resources 'users' do
      member do
        patch :archive
      end
    end
    resources 'programs'
    resources 'materials'
    resources 'machines'
    resources 'occupation'
    resources 'rentings'
    resources 'information'
    resources 'fabmoments' do
      member do
        get :staff_pick
      end
    end
    resources 'events' do
      member do
        get :approved
      end
    end
    get 'fabmanager_settings/1', to: 'fabmanager_settings#settings'
    resources 'fabmanager_settings', only: [:update]
  end

  devise_for :users

  resources 'information'
  resources 'users'
  resources :avatar
  resources 'machines' do
    member do
      get :take
      get :leave
    end
  end



  root 'fabmoments#index'
  get '/fabmoment/index', :controller => 'fabmoments', :action => "index"
  post '/fabmoment/index', :controller => 'fabmoments', :action => "index"

  resources 'fabmoments' do
    member do
      get :like
      get :unlike
    end
    collection do
      get :search
    end
    resources 'tags' do
      member do
        delete :remove
      end
    end
    resources 'project_files', only: [:create, :destroy]
    resources 'comments', only: [:create, :edit, :update, :destroy]
  end
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :interfaces, :dependent => :destroy
  has_many :fabmoments, :through => :interfaces
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < ApplicationController
	before_action :set_program, only: [:show, :edit, :update, :destroy, :archive]
	def index
		@programs = Program.all
	end
	def new
		@programs = Program.new
	end
  def show
  end
  def edit
  end
   def update
    @programs = Program.find(params[:id])
    if @programs.update(programs_params)
      flash[:notice] = "Programma is succesvol geëdit."
      redirect_to admin_programs_path
    else
      render 'edit'
    end
  end
	def create
		@programs = Program.new(programs_params)

    if @programs.save
      flash[:notice] = "Programma is succesvol toegevoegd."
      redirect_to admin_programs_path
    else
      flash.now[:alert] = "Programma is niet toegevoegd."
    end
	end
	 def destroy
    @programs = Program.find(@programs)
    @programs.delete
    redirect_to admin_programs_path
  end
    def programs_params
    	params.require(:program).permit(:id,:name,:admin)
    end
    def set_program
    @programs = Program.find(params[:id])
  	end
	
end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/views/admin/programs/_form.html.erb
<div class="w3-row">
	<div class="w3-half w3-center" style="margin-left: 25%">
		<%= simple_form_for [:admin, @programs] do |f| %>
			<!-- Input -->
			<%= f.input_field :name, required: true, autofocus: true %>
			<%= f.label :name %>
			<%= f.error :name %>
			
			<br><br>
      <!-- Zenden -->
      <div class="w3-center w3-margin-bottom">
        <%= f.button :button, class: "w3-btn w3-blue w3-center" %>
      </div>

		<% end %>
	</div>
</div>

app/views/admin/programs/edit.html.erb
<div class="w3-container w3-margin-top">
	<header>
		<h2 class="w3-center">Nieuw Programma</h2>
	<header>
</div>

<%= render "form", program: @programs %>

app/views/admin/programs/index.html.erb
<p>
<ul>
  <div class="row">
    <div class="col w3-card w3-round-xlarge">
      <div class="w3-margin-left w3-margin-bottom">
        <div class="w3-bottombar w3-border-blue-gray">
          <h1>Materialen:</h1>
        </div>
      <% @programs.each do |program| %>
          <li><%= program.name%></li>

          <%= link_to admin_program_path(program), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger w3-round-xlarge"  do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
          <%= link_to edit_admin_program_path(program), class:"btn btn-warning w3-round-xlarge"  do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
      <% end %>
      <div class="w3-topbar w3-border-blue-gray w3-margin-top">
        <%= link_to "Nieuw Programma", [:new, :admin, :program],
                    class: "new w3-btn w3-lime w3-margin-bottom w3-margin-top w3-round-xlarge w3-topbar w3-border-blue-gray w3-hover-blue"%>
        </div>
      </div>
    </div>
  </div>
</ul>
</p>

app/views/admin/programs/new.html.erb
<% title("Nieuw", "Machine") %>

<div class="w3-container w3-margin-top">
	<header>
		<h2 class="w3-center">Nieuw Programma</h2>
	<header>
</div>

<%= render "form", program: @programs %>