config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'events_api#redirect', as:'redirect'
  get '/callback', to: 'events_api#callback', as:'callback'
  get '/calendars', to: 'events_api#calendars', as: 'calendars'
  get '/events_api/:calendar_id', to: 'events_api#retrieve_events', as: 'events_api', calendar_id: /[^\/]+/
  resources :events, controller: 'events'

  resources :meetings
  namespace :admin do
    root 'application#index'
    resources 'users' do
      member do
        patch :archive
      end
    end
    resources 'programs'
    resources 'materials'
    resources 'machines'
    resources 'occupation'
    resources 'rentings'
    resources 'information'
    resources 'fabmoments' do
      member do
        get :staff_pick
      end
    end
    resources 'events' do
      member do
        get :approved
      end
    end
    get 'fabmanager_settings/1', to: 'fabmanager_settings#settings'
    resources 'fabmanager_settings', only: [:update]
  end

  devise_for :users

  resources 'information'
  resources 'users'
  resources :avatar
  resources 'machines' do
    member do
      get :take
      get :leave
    end
  end



  root 'fabmoments#index'
  get '/fabmoment/index', :controller => 'fabmoments', :action => "index"
  post '/fabmoment/index', :controller => 'fabmoments', :action => "index"

  resources 'fabmoments' do
    member do
      get :like
      get :unlike
    end
    collection do
      get :search
    end
    resources 'tags' do
      member do
        delete :remove
      end
    end
    resources 'project_files', only: [:create, :destroy]
    resources 'comments', only: [:create, :edit, :update, :destroy]
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "Alleen admins krijgen hier toegang."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    flash[:alert] = "Je moet ingeschreven zijn om deze actie te ondergaan."
    redirect_to(new_user_session_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :avatar_cache, :remove_avatar, :first_name, :surname, :date_of_birth, :gender, :country, :province, :city])
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :avatar_cache, :remove_avatar, :first_name, :surname, :date_of_birth, :gender, :country, :province, :city])
    # devise_parameter_sanitizer.permit(:edit, keys: [:username, :avatar, :avatar_cache, :remove_avatar, :first_name, :surname, :date_of_birth, :gender, :country, :province, :city])
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "FabLab").join(" - ")
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def open_inloop
    settings = FabmanagerSettings.find(1)
    @openinloop = settings.open_hour
  end
end

app/views/admin/application/index.html.erb
<% title("Admin") %>

<div class="w3-container w3-center w3-border-blue-grey w3-padding-xlarge">
	<header class="w3-center w3-margin-top">
		<h2 class="w3-round-xlarge w3-lime w3-padding w3-margin-bottom">Fablab Zeeland Manager</h2>
		<% if current_user %>
			<ul class="actions w3-ul">
        <li>
							  <%= link_to "Gebruikers", admin_users_path,
								class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
								<%= link_to "Programma's", admin_programs_path,
								class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
								<%= link_to "Machines", admin_machines_path,
								class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
								<%= link_to "Materialen", admin_materials_path,
								class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
                <%= link_to "Evenementen", admin_events_path,
                class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
                <%= link_to "Fabmomenten", admin_fabmoments_path,
                class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
                <%= link_to "Open-inloop Settings", admin_fabmanager_settings_1_path,
                class: "new w3-btn w3-round-xlarge w3-lime w3-margin-bottom"%>
        </li>
			</ul>
		<% end %>
	</header>
</div>