config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'events_api#redirect', as:'redirect'
  get '/callback', to: 'events_api#callback', as:'callback'
  get '/calendars', to: 'events_api#calendars', as: 'calendars'
  get '/events_api/:calendar_id', to: 'events_api#retrieve_events', as: 'events_api', calendar_id: /[^\/]+/
  resources :events, controller: 'events'

  resources :meetings
  namespace :admin do
    root 'application#index'
    resources 'users' do
      member do
        patch :archive
      end
    end
    resources 'programs'
    resources 'materials'
    resources 'machines'
    resources 'occupation'
    resources 'rentings'
    resources 'information'
    resources 'fabmoments' do
      member do
        get :staff_pick
      end
    end
    resources 'events' do
      member do
        get :approved
      end
    end
    get 'fabmanager_settings/1', to: 'fabmanager_settings#settings'
    resources 'fabmanager_settings', only: [:update]
  end

  devise_for :users

  resources 'information'
  resources 'users'
  resources :avatar
  resources 'machines' do
    member do
      get :take
      get :leave
    end
  end



  root 'fabmoments#index'
  get '/fabmoment/index', :controller => 'fabmoments', :action => "index"
  post '/fabmoment/index', :controller => 'fabmoments', :action => "index"

  resources 'fabmoments' do
    member do
      get :like
      get :unlike
    end
    collection do
      get :search
    end
    resources 'tags' do
      member do
        delete :remove
      end
    end
    resources 'project_files', only: [:create, :destroy]
    resources 'comments', only: [:create, :edit, :update, :destroy]
  end
end

app/models/fabmoment.rb
class Fabmoment < ApplicationRecord
  # Main Models
  belongs_to :author, class_name: "User"
  validates :title, length: { in: 4..25 }
  validates :description, length: { minimum: 20 }
  # Fabmoment to interface with programs.
  has_many :interfaces, :dependent => :destroy
  has_many :programs, :through => :interfaces
  # Fabmoment to handle machines.
  has_many :handles, :dependent => :destroy
  has_many :machines, :through => :handles
  # Fabmoment to feed materials.
  has_many :feeds, :dependent => :destroy
  has_many :materials, :through => :feeds
  # Fabmoment has many tags (and vice versa).
  has_and_belongs_to_many :tags, uniq: true
  attr_accessor :tag_names
  # Fabmoment has many comments
  has_many :comments, dependent: :destroy
  # Fabmoment needs 1 license
  belongs_to :license
  #fabmoment has many pictures
  has_many :pictures, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :pictures
  #fabmoment has many project_files
  has_many :project_files, dependent: :destroy
  accepts_nested_attributes_for :project_files

  acts_as_votable


  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end

  def self.search(search)
    query = "%#{search.downcase}%"
    if search
      results = self.where('lower(title) LIKE ? or lower(description) LIKE ?', query, query).order(:created_at)
      result_tags = Tag.where('lower(name) LIKE ?', query)
      result_machines = Machine.where('lower(name) LIKE ?', query)
      result_tags.each do |tag|
        results += self.includes(:tags).where(tags: { id: tag.id })
      end
      result_machines.each do |machine|
        results += self.includes(:machines).where(machines: { id: machine.id })
      end
    else
      results = self.all
    end
    results.uniq{|x| x.id}
  end
    # def search(search)
    #   query = "%#{search.downcase}%"
    #   @result = Fabmoment.search('lower(title) LIKE ?', query)
    #           + Fabmoment.search('lower(description) LIKE ?', query) 
    #           + Tag.search('lower(name) LIKE ?', query)
    # end
end

app/controllers/admin/fabmoments_controller.rb
class Admin::FabmomentsController < ApplicationController
  before_action :set_fabmoment, only: [:show, :edit, :update, :destroy]

  def index
    @fabmoments = Fabmoment.all
    @machines = Machine.all
    @openingtimes = Openingtime.first
  end


  def staff_pick
    fabmoment = Fabmoment.find(params[:id])
    fabmoment.toggle! :staff_pick
    redirect_to(:back)
  end
end

app/controllers/fabmoments_controller.rb
class FabmomentsController < ApplicationController
  before_action :set_fabmoment, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :set_programs, only: [:new, :create, :edit, :update]
  before_action :set_machines, only: [:new, :create, :edit, :update]
  before_action :set_materials, only: [:new, :create, :edit, :update]

  def index
    @fabmoments = Fabmoment.all
    @machines = Machine.all
    @openingtimes = Openingtime.first
    @events = Event.all.where(approved: true)
  end

  def show
    @comment = @fabmoment.comments.build
  end

  def new
    @fabmoment = Fabmoment.new
  end

  def create
    @fabmoment = Fabmoment.new(fabmoment_params)
    @fabmoment.author = current_user

    if @fabmoment.save
      if params[:images]
        params[:images].each do |image|
          @fabmoment.pictures.create(image: image)
        end
      end
      if params[:files]
        params[:files].each do |file|
          @fabmoment.project_files.create(file: file)
        end
      end
      flash[:notice] = "Fabmoment is succesvol toegevoegd."
      redirect_to @fabmoment
    else
      flash.now[:alert] = "Fabmoment is niet toegevoegd."
      render "new"
    end
  end

  def edit
    authorize @fabmoment, :edit?
  end

  def update
    if @fabmoment.update(fabmoment_params) 
      if params[:images]
        params[:images].each do |image|
          @fabmoment.pictures.create(image: image)
        end
      end
      if params[:files]
        params[:files].each do |file|
          @fabmoment.project_files.create(file: file)
        end
      end
      flash[:notice] = "Fabmoment is bijgewerkt."
      redirect_to @fabmoment
    else
      flash.now[:alert] = "Fabmoment is niet bijgewerkt."
      render "edit"
    end
  end

  def like
    @fabmoment.liked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
      end
    end

  def unlike
    @fabmoment.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def destroy
    authorize @fabmoment, :destroy?
    @fabmoment.destroy
    flash[:notice] = "Fabmoment is verwijderd."
    #redirect_to fabmoments_path 
  end

  def search
    if params[:search].present?
      @fabmoments = Fabmoment.all.search(params[:search])
    else
      @fabmoments = Fabmoment.all
    end
    @machines = Machine.all
    @openingtimes = Openingtime.first
    @events = Event.all.where(approved: true)
    render 'fabmoments/index'
  end

  private


  def fabmoment_params
    params.require(:fabmoment).permit(:title, :description, :source, :gingGoed, :gingFout, :kanBeter,  :license_id, :tag_names,
      :program_ids => [], :machine_ids => [], :material_ids => [], pictures_attributes: [:image], project_files_attributes: [:file] )
  end

  def set_fabmoment
    @fabmoment = Fabmoment.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Het fabmoment waar je naar zocht is niet hier."
    redirect_to fabmoments_path
  end

  def set_programs
    @programs = Program.all
  end

  def set_machines
    @machines = Machine.all
  end

  def set_materials
    @materials = Material.all
  end
end

app/helpers/admin/fabmoments_helper.rb
module Admin::FabmomentsHelper
end

app/helpers/fabmoments_helper.rb
module FabmomentsHelper

end

app/views/fabmoments/_countdown_timer.html.erb
<h1 class="" style="color: #00bcd4">Open Inloop.</h1>
<!-- Display the countdown timer in an element -->
<p id="demo"></p>
<script>
    // Set the date we're counting down to
    var countDownDate = new Date("April 18, 2017 15:37:25").getTime();

    // Update the count down every 1 second
    var x = setInterval(function() {

        // Get todays date and time
        var now = new Date().getTime();

        // Find the distance between now an the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds


        var days = Math.floor(distance / (<%= 50 %> * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Display the result in the element with id="demo"
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
            + minutes + "m " + seconds + "s ";

        // If the count down is finished, write some text
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "Er zijn nu geen machines in gebruik";
        }
    }, 1000);
</script>

app/views/fabmoments/_fabmoments_gallery.html.erb
<div id="fabmoments" class="w3-row-padding w3-margin-top">
  <% fabmoments.each do |fabmoment| %>
      <%= link_to fabmoment do %>
          <div class="w3-col m3 w3-text-yellow">
            <div class="w3-card-2 w3-hover-shadow w3-margin-bottom">
              <%= link_to fabmoment do %>
              <header class="w3-container w3-lime w3-padding-top">

                <%= link_to [:staff_pick, :admin, fabmoment] do %>
                    <i class="w3-left fa fa-star w3-show-inline-block w3-hover-opacity w3-large <%= fabmoment.staff_pick? ? 'w3-text-blue' : 'fa fa-star-o w3-text-blue-gray w3-hover-gray' %>"></i>
                <% end %>

                <h4 class="w3-show-inline-block w3-center"><%= link_to fabmoment do %><%= fabmoment.title %></h4>

                <div id="fabmoment-likes-ajax-<%= fabmoment.id %>" class="w3-right w3-show-inline-block w3-large">
                   <%= render 'fabmoments/likes', fabmoment: fabmoment %>
                 </div>
                  <% end %>
              </header>
              <div class="w3-container w3-white">
                <%  if fabmoment.pictures.any? %>
                <%= image_path fabmoment.pictures.first %>
                    <% else %>
                <!--<img src="/images/450x300-placeholder.png">-->
                    <% end %>
                <div>
                  <%= truncate(fabmoment.description, length: 350) %>
                </div>
              </div>
                  <% end %>
            </div>
      <% end %>
      </div>
  <% end %>
</div>


app/views/fabmoments/_favourite_gallery.html.erb
<div id="fabmoment" class="jumbotron-icon">

  <div class="w3-bar w3-lime w3-round-xxlarge w3-center">
    <h3 class="w3-medium">Highlights.</h3>
  </div>

  <% @fabmoments.where(staff_pick: true).last(5).each do |fabmoment| %>
      <div class="mySlides">
        <div class="w3-display-container">
          <img class="w3-margin-top w3-padding w3-round-xxlarge w3-animate-fading" src="http://via.placeholder.com/800x500" style="width:100%">

          <div class="w3-display-bottommiddle w3-container w3-center" style="width: 100%;">
            <div class="w3-left fa fa-6 fa-caret-left w3-text-lime w3-hover-opacity" onclick="plusDivs(-1)"></div>
            <div class="w3-right fa fa-6 fa-caret-right w3-text-lime w3-hover-opacity" onclick="plusDivs(1)"></div>
            <% @fabmoments.where(staff_pick: true).last(5).size.times do |i| %>
                <span class="w3-badge w3-hover-opacity-max demo w3-border w3-center" onclick="currentDiv(<%= i+1 %>)"></span>
            <% end %>
          </div>

        </div>
        <div class="w3-center">

          <h1><%= fabmoment.title %></h1>

          <%= truncate(fabmoment.description, length: 500) %>
          <div>
            <%= link_to 'Nieuw Fabmoment', new_fabmoment_path, class:"new w3-btn w3-lime w3-margin-bottom w3-margin-top w3-round-xlarge w3-topbar w3-border-blue-gray w3-hover-blue" %>
          </div>
        </div>
      </div>

  <% end %>
</div>

<script>
    var slideIndex = 1;
    showDivs(slideIndex);
    carousel();

    function plusDivs(n) {
        showDivs(slideIndex += n);
    }

    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) {slideIndex = 1}
        if (n < 1) {slideIndex = x.length} ;
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        x[slideIndex-1].style.display = "block";
    }

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > x.length) {slideIndex = 1}
        x[slideIndex-1].style.display = "block";
        setTimeout(carousel, 5000); // Change image every 5 seconds
    }
</script>

app/views/fabmoments/_form.html.erb
<div class="w3-row-">
    <div class="w3-twothird" style="margin-left: 16.65%">

      <%= simple_form_for @fabmoment, html: {multipart: true} do |f| %>

      	<!-- Input -->
          <%= f.label :title %>
        <%= f.input_field :title %>
        <%= f.error :title %>
          <%= f.label :description %>
      	<%= f.input_field :description, rows: 7 %>
        <%= f.error :description %><br><br>
        <!-- Gallery -->

          <!-- Zoom -->
          <div id="modal01" class="w3-modal" onclick="this.style.display='none'">
            <span class="w3-closebtn w3-hover-red w3-text-white w3-xxlarge w3-container w3-display-topright">&times;</span>
            <div class="w3-modal-content w3-animate-zoom">
              <img id="img01" style="width:100%">
            </div>
          </div>

        <!-- Upload picture -->
        <div class="w3-center">
          <%= f.label :pictures %>
          <%= file_field_tag 'images[]', type: :file, multiple: true %>
          <p>Geldige bestanden: .png .jpg .gif</p>
        </div>
        <br>

        <!-- Upload Project Files-->
        <div class="w3-center">
          <%= f.label :project_files %>
          <%= file_field_tag 'files[]', type: :file, multiple: true %>
          <p>Geldige bestanden: .stl .obj .doc .txt</p>
        </div>
        <br><br>

        <div class="w3-row-padding w3-margin-top">
          <!-- Programs card -->
          <div class="w3-col m3">
            <div class="w3-card w3-round-xlarge">
              <header class="w3-container w3-lime">
              <h5 class="w3-center">Programma's</h5>
              </header>
              <ul class="w3-ul" id="programs">
              <%= f.collection_check_boxes :program_ids, @programs, :id, :name do |b| %>
                <li>
                  <%= b.label class: "w3-small" do %>
                    <%= b.check_box class: "w3-check" %>
                    <%= b.text %>
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
          <!-- Machines card -->
          <div class="w3-col m4">
            <div class="w3-card w3-round-xlarge">
              <header class="w3-container w3-lime">
                <h5 class="w3-center">Machines</h5>
              </header>
              <ul class="w3-ul" id="machines">
              <%= f.collection_check_boxes :machine_ids, @machines, :id, :name do |b| %>
                <li>
                  <%= b.label class: "w3-small" do %>
                    <%= b.check_box class: "w3-check" %>
                    <%= b.text %>
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
          <!-- Materials card -->
          <div class="w3-col m5">
            <div class="w3-card w3-round-xlarge w3-margin-bottom">
              <header class="w3-container w3-lime">
                <h5 class="w3-center">Materialen</h5>
              </header>
              <ul class="w3-ul" id="materials">
              <%= f.collection_check_boxes :material_ids, @materials, :id, :full_name do |b| %>
                <li>
                  <%= b.label class: "w3-small" do %>
                    <%= b.check_box class: "w3-check" %>
                    <%= b.text %>
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>


        <!-- Upload: Project Files -->
        <!-- Stored -->

        <!-- Upload -->
 

        <% if @fabmoment.tags.any? %>
          <div id="tags">
            <%= render @fabmoment.tags, fabmoment: @fabmoment %>
          </div>
        <% end %>

        <br>
        <%= f.input_field :tag_names %>
        <%= f.label :tag_names %>
        <%= f.error :tag_names %>

        <br><br>
        <!-- Creative Commons -->
        <%= f.collection_select(:license_id, License.all, :id, :title) %>
        <br><br>
        <!-- Source -->
        <%= f.input_field :source %>
        <%= f.label :source %>
        <br><br>
        <!-- Wat ging er goed/Wat ging er fout -->
        <%= f.input_field :gingGoed, rows: 4 %>
        <%= f.label :gingGoed %>

        <%= f.input_field :gingFout, rows: 4 %>
        <%= f.label :gingFout %>

        <%= f.input_field :kanBeter, rows: 4 %>
        <%= f.label :kanBeter %>




        <!-- Zenden -->
        <div class="w3-center w3-margin-bottom">
          <%= f.button :button, class: "w3-btn w3-blue w3-center" %>
        </div>

      <% end %>

  </div>
</div>

app/views/fabmoments/_likes.html.erb
<div class=”likes” id=”likes_<%= fabmoment.id %>”>
  <div class="w3-hover-opacity">
    <% if user_signed_in? %>
      <% if current_user.voted_for? fabmoment %>
        <%= link_to '', [:unlike, fabmoment], remote: true, class: "fa fa-heart w3-text-red" %>
      <% else %>
        <%= link_to '', [:like, fabmoment], remote: true, class: "fa fa-heart-o w3-text-blue-gray" %>
    <% end %>
        <% else %>
    <i class="fa fa-heart-o w3-text-blue-gray" aria="hidden"></i>
      <% end %>
    <div class="w3-text-white w3-small w3-show-inline-block">
    <%= "&times;".html_safe + fabmoment.votes_for.size.to_s if fabmoment.votes_for.size>0 %>
    </div>
  </div>
</div>




app/views/fabmoments/_locationmaps.html.erb
<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script>
    handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'one_marker'}}, function(){
        markers = handler.addMarkers([
            {
                lat: 51,
                lng: 3,
                picture: {
                    url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                    width:  36,
                    height: 36
                },
                infowindow: "hello!"
            }
        ]);
    });
</script>

<div style='width: 800px;'>
  <div id="one_marker" style='width: 800px; height: 400px;'></div>
</div>

app/views/fabmoments/_searchbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group" id="adv-search">

        <!--<input type="text" class="form-control" placeholder="Zoek voor fabmomenten"/>-->

        <div class="form-control"><%= form_tag search_fabmoments_path, method: :get, class: "" do %></div>
            <%= text_field_tag "search", params[:search], class:"", placeholder: "Zoek voor fabmomenten" %>

        <div class="input-group-btn">
          <div class="btn-group" role="group">
            <div class="dropdown dropdown-lg">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                      aria-expanded="false"><span class="caret"></span>
              </button>
              <div class="dropdown-menu dropdown-menu-right" role="menu">
                <form class="" role="form">
                  <div class="form-group">
                    <label for="filter">Filter by</label>
                    <select class="form-control">
                      <option value="0" selected="selected">All Snippets</option>
                      <option value="1">Featured</option>
                      <option value="2">Most popular</option>
                      <option value="3">Top rated</option>
                      <option value="4">Most commented</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="contain">Author</label>
                    <input class="form-control" type="text" />
                  </div>
                  <div class="form-group">
                    <label for="contain">Contains the words</label>
                    <input class="form-control" type="text" />
                  </div>
                  <button <%= submit_tag "Zoek", class: "btn w3-blue" %>><span class="fa fa-search" aria-hidden="true"></span>
                  </button>
                </form>
              </div>
            </div>
            <!--<button type="button" class="btn w3-blue"><span class="fa fa-search" aria-hidden="true"></span>-->
            <button <%= submit_tag "Zoek", class: "btn w3-blue" %>Zoek <span class="fa fa-search" aria-hidden="true"></span>
            </button>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fabmoments/destroy.js.erb
$("#fabmoment-ajax-<%= @fabmoment.id %>").remove();

app/views/fabmoments/edit.html.erb
<% title(@fabmoment.title, "Fabmoments") %>

<div class="w3-container">
	<header class="w3-center">
		<h1><%= @fabmoment.title %></h1>
	<header>
</div>

<%= render "form", fabmoment: @fabmoment %>

app/views/fabmoments/like.js.erb
$("#fabmoment-likes-ajax-<%= @fabmoment.id %>").html("<%= j render 'fabmoments/likes', fabmoment: @fabmoment %>");

app/views/fabmoments/new.html.erb
<% title("Nieuw", "Fabmoments") %>

<div class="w3-container">
	<header class="w3-center">
		<h1 class="w3-margin-top w3-round-xlarge w3-lime w3-padding">Nieuw Fabmoment</h1>
    <%= render "form", fabmoment: @fabmoment %>
	</header>
</div>

app/views/fabmoments/show.html.erb
<% title(@fabmoment.title, "Fabmoments") %>

<div class="w3-row w3-center w3-topbar w3-co w3-border-blue-grey w3-padding-xlarge" style="color: 009ee3" >
	<div class="w3-twothird" style="margin-left: 16.65%">

		<header class="w3-center w3-bottombar w3-border-blue-grey">
			<h1><%= @fabmoment.title %></h1>
			<p class="w3-text-pink">
				Door
				<b class="w3-btn w3-pink w3-padding-tiny w3-padding-left w3-padding-right">
					<%= link_to @fabmoment.author.username, user_path(@fabmoment.author) %>
				</b>
				<%= " aangemaakt #{time_ago_in_words(@fabmoment.created_at)} geleden" %>
				<!-- De fout in bovenstaande link_to zit hem erin dat je als admin
						 naar admin_user_path zou moeten gaan, tenzij je geen admin namespace
						 gebruikt en alles met één controller + pundit regelt. -->
			</p>
		</header>

		<p><%= @fabmoment.description %></p>

		<!-- Gallery -->
		<div id="images">
			<div class="w3-row-padding">
				<% @fabmoment.pictures.each do |p| %>
				  <div class="w3-container w3-quarter">
				    <img src="<%= p.image.url %>" style="width:100%;cursor:pointer"
				    onclick="onClick(this)" class="w3-hover-opacity">
				  </div>
				<% end %>
			</div>
		</div>

		<!-- Gallery: Zoom -->
		<div id="modal01" class="w3-modal" onclick="this.style.display='none'">
		  <span class="w3-closebtn w3-hover-red w3-text-white w3-xxlarge w3-container w3-display-topright">&times;</span>
		  <div class="w3-modal-content w3-animate-zoom">
		    <img id="img01" style="width:100%">
		  </div>
		</div>

		<div class="w3-row-padding w3-margin-top">
		<% if @fabmoment.programs.any? %>
			<div class="w3-col m3">
        <div class="w3-card">
          <h5 class="w3-center">Programma's</h5>
          <ul id="programs">
						<% @fabmoment.programs.each do |program| %>
							<p><%= program.name %></p>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>

		<!-- Project Files -->
		<div id="project-files">
			<div class="w3-col m3">
				<% @fabmoment.project_files.each do |files| %>
				  <div class="w3-container">
				    <u style="color:blue"><%= link_to files.file_file_name, files.file.url(original: false) %></u>
				  </div>
				<% end %>
			</div>
		</div>

		<!-- Machine and Material cards -->
		<% if @fabmoment.machines.any? %>
			<div class="w3-col m4">
        <div class="w3-card">
          <h5 class="w3-center">Machines</h5>
          <ul id="machines">
						<% @fabmoment.machines.each do |machine| %>
							<p><%= machine.name %></p>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>
		<% if @fabmoment.materials.any? %>
			<div class="w3-col m5">
        <div class="w3-card">
          <h5 class="w3-center">Materialen</h5>
          <ul id="materials">
						<% @fabmoment.materials.each do |material| %>
							<p><%= material.full_name %></p>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>
		</div>

		<br>
			<%= @fabmoment.license.title %>
		<br>
		<br>
      <div>
        <%= link_to @fabmoment.source, @fabmoment.source, {:class => "sourcelink"}%>
      </div>
		<br>
		<br>
			<h4 class="w3-text-black"> Wat ging er goed ?</h4>
			<p><%= @fabmoment.gingGoed %></p>
		<br>
		<br>
			<h4 class="w3-text-black"> Wat ging er fout ?</h4>
			<p><%= @fabmoment.gingFout %></p>
		<br>
		<br>
			<h4 class="w3-text-black"> Wat kan beter ?</h4>
			<p><%= @fabmoment.kanBeter %></p>
		<br>
		<!-- Fabmoment model moet de project files scopen, vergelijkbaar
				 met de persisted method in het Comment model.
				 Vind in de console uit hoe deze scope eruit moet zien. -->

		<% if @fabmoment.tags.any? %>
			<div id="tags" class="w3-margin-top">
				<%= render @fabmoment.tags, fabmoment: @fabmoment %>
			</div>
		<% end %>

		<footer class="w3-center w3-bottombar w3-border-blue-grey w3-padding-xlarge">
			<br>
			<% if policy(@fabmoment).update? %>
				<%= link_to "Bijwerken Fabmoment", [:edit, @fabmoment],
								class: "edit w3-btn w3-amber" %>
			<% end %>
			<% if policy(@fabmoment).destroy? %>
				<%= link_to "Verwijder Fabmoment", [@fabmoment],
								method: :delete, remote: true,
								data: { confirm: "Weet je zeker dat je het fabmoment wil verwijderen?"},
								class: "delete w3-btn w3-red" %>
			<% end %>
		</footer>

		<div id="comments" class="w3-half w3-margin-top" style="margin-left: 25%">
			<% if @fabmoment.comments.persisted.any? %>
				<% @fabmoment.comments.persisted.each do |comment| %>
					<div id="comment-ajax-<%= comment.id %>">
						<%= render comment %>
					</div>
				<% end %>

				<%#= render @fabmoment.comments.persisted, fabmoment: @fabmoment %>
			<% else %>
				<p class="w3-text-dark-grey w3-padding w3-center">
					Er zijn geen commentaren op dit fabmoment.
				</p>
			<% end %>
			<% if policy(@fabmoment).comment? %>
				<%= render 'comments/form', fabmoment: @fabmoment,
											comment: @fabmoment.comments.build %>
			<% end %>
		</div>
	</div>
</div>


<!-- Dit stukje moet naar fabmoments.coffee als coffeescript ! -->
<script>
	function onClick(element) {
	  document.getElementById("img01").src = element.src;
	  document.getElementById("modal01").style.display = "block";
	}
</script>

app/views/fabmoments/snippet.html.erb
        <strong>Machines</strong>
        <% @machines.each do |m| %>
          <br>
          <!-- f.input_field :remember_me, as: :boolean -->
          <%= f.label m.name %>
          <%= f.check_box %>
        <% end %>

app/views/fabmoments/unlike.js.erb
$("#fabmoment-likes-ajax-<%= @fabmoment.id %>").html("<%= j render 'fabmoments/likes', fabmoment: @fabmoment %>");